# We pinned the base game v0.7.0 for now.
[game-cbn-tiles-stable-prebuilt]
src.github_tag = "cataclysmbnteam/Cataclysm-BN"
fetch.tarball = "https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/v0.7.0/cbn-linux-tiles-x64-v0.7.0.tar.gz"

# Pinned to supported v0.7.0 version
[mod-tankmod-revived]
src.manual = "8f656072e519be699e6a4caf78ca69451db6d290"
fetch.github = "chaosvolt/cdda-tankmod-revived-mod"
pinned = true

[mod-jackledead-armory]
src.git = "https://github.com/jackledead/jackledead_armory"
fetch.github = "jackledead/jackledead_armory"

[soundpack-otopack]
src.git = "https://github.com/Kenan2000/Otopack-Mods-Updates"
fetch.github = "Kenan2000/Otopack-Mods-Updates"
