[game-cbn-tiles-stable-prebuilt]
src.github_tag = "cataclysmbnteam/Cataclysm-BN"
src.include_regex = "v\\d+.\\d+.\\d+"
fetch.tarball = "https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/$ver/cbn-linux-tiles-x64-$ver.tar.gz"

# Tankmod is pinned atm because latest updates aren't compatible with cbn v0.6.0
[mod-tankmod-revived]
src.manual = "11a52995bdbdd9bc5ec66b058a5aaef755f96691"
fetch.github = "chaosvolt/cdda-tankmod-revived-mod"
pinned = true

[mod-jackledead-armory]
src.git = "https://github.com/jackledead/jackledead_armory"
fetch.github = "jackledead/jackledead_armory"

[soundpack-otopack]
src.git = "https://github.com/Kenan2000/Otopack-Mods-Updates"
fetch.github = "Kenan2000/Otopack-Mods-Updates"
