# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  game-cbn-tiles-nightly-prebuilt = {
    pname = "game-cbn-tiles-nightly-prebuilt";
    version = "2024-11-22";
    src = fetchTarball {
      url = "https://github.com/cataclysmbnteam/Cataclysm-BN/releases/download/2024-11-22/cbn-linux-tiles-x64-2024-11-22.tar.gz";
      sha256 = "sha256-nXwqHIu29xiTHChPKwnLcpXd0/x73ba0S8pUoXBByiA=";
    };
  };
  mod-jackledead-armory = {
    pname = "mod-jackledead-armory";
    version = "7262ba982a83f37cb1b12cac58e5f053a44a1833";
    src = fetchFromGitHub {
      owner = "jackledead";
      repo = "jackledead_armory";
      rev = "7262ba982a83f37cb1b12cac58e5f053a44a1833";
      fetchSubmodules = false;
      sha256 = "sha256-ta0JTM9asi+7CgdEM0KqjkqD2QQqkdTRbHTdwWthxB8=";
    };
    date = "2024-11-19";
  };
  mod-tankmod-revived = {
    pname = "mod-tankmod-revived";
    version = "90dd870d4465ab1c9b40d7d139017084abaffc3b";
    src = fetchFromGitHub {
      owner = "chaosvolt";
      repo = "cdda-tankmod-revived-mod";
      rev = "90dd870d4465ab1c9b40d7d139017084abaffc3b";
      fetchSubmodules = false;
      sha256 = "sha256-YZCHWhlkbN7BeHmYMHuC04VoQxsXwPf3uHKc+BaKz8c=";
    };
    date = "2024-11-18";
  };
  soundpack-otopack = {
    pname = "soundpack-otopack";
    version = "508da9f0e38ec996f14c930c58848024680ca2be";
    src = fetchFromGitHub {
      owner = "Kenan2000";
      repo = "Otopack-Mods-Updates";
      rev = "508da9f0e38ec996f14c930c58848024680ca2be";
      fetchSubmodules = false;
      sha256 = "sha256-t8MplRma2A2yVw9P8SU4rf7lt1dP2KWna7EQfakZ1Zg=";
    };
    date = "2024-08-10";
  };
}
